# Workflow Name
name : First Workflow
# Trigger
on : 
  push :
  workflow_dispatch: # manual
 
jobs:
   # First Job
  Hello-job:
     # runner - Github hosted
     runs-on : ubuntu-latest
     steps:
       - name : Hello World
         run : echo "Hello World"
       - name : Event Name
         run : echo "Event Name :${{github.event_name}}" # Context Reference
